version:  "3"
services:
  mssql_admin:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SU2orange!"
    ports:
      - "14330:1433"
    hostname: mssql_admin
    volumes:
      - "mssql-azuresql-edge-data_param:/var/opt/mssql"
  sc_parametrodetalle_back:
    image: cargaexcel
    environment:
      - "CONNECTION_STRING=Data Source=mssql_admin,1433;Initial Catalog=ADMINISTRADOR;User Id=sa;Password=SU2orange!;"     
    ports:
      - "8082:80"    
    depends_on:
      - mssql_admin
volumes:
    mssql-azuresql-edge-data_param: